### ISSUE TITLE
GestureTest Example 

### ISSUE THREAD

**Issue by seijimadrigal** [Depau/APDS9930#13]
Thanks for the library!  The Gesture Test example sketch is not included in the examples folder, it would be a great help if you included an example of gesture controls for the module.

**Comment by depau** [comment]
@souljaz05 This sensor does not support gesture recognition.

**Comment by seijimadrigal** [comment]
Hello, thanks for the reply, I just realised that it doesn't and also made the mistake of buying this module instead of the 9960.

**Comment by depau** [comment]
@souljaz05 Just like everyone else 😂😂 everyone buys the 9930 thinking it's a 9600, myself included
