### ISSUE TITLE
apds-9930 proximity sensor not working

### ISSUE THREAD

**Issue by TechnicallyCoded** [Depau/APDS9930#15]
I know that this is a duplicate but I am creating this in hope that some will explain in detail why some apds-9930 proximity sensor doesn't work even though ambient light does work

Answers I have seen:
Led is not getting any current -> how should it be powered then?
There is a pin to power the led -> can you not just say which one?

**Comment by ElFishi** [comment]
depends on your breakout board. 
some have jumpers to select from where the LED anode should be powered. 
choices are: 
- the Vcc pin also powering the chip (3.3V) or
- a separate VL pin (max. 4.5V).

**Comment by TechnicallyCoded** [comment]
Thank you so much I can now actually get readings even if the distance given seems to be inverted (1023 when close 200 when far) but at least its not random ! 
I will consider this resolved : )
In my case, I had the VL pin to connect if anyone sees this in the future
