### ISSUE TITLE
The ALS coefficients defined name B make bearssl_ec.h in ESP8266 Arduino Core  syntax error

### ISSUE THREAD

**Issue by codemee** [Depau/APDS9930#20]
In bearssl_ec.h of ESP8266 Arduino Core, there's a function prototype as bellow

uint32_t (*muladd)(unsigned char *A, const unsigned char *B, size_t len,
		const unsigned char *x, size_t xlen,
		const unsigned char *y, size_t ylen, int curve);

The ALS coefficients defined name B would make this syntax erorr while expanding B as 1.862.

**Comment by depau** [comment]
@codemee Hi, thanks for reporting. Would you mind sending a pull request to resolve the issue?

Thank you very much

**Comment by codemee** [comment]
No problem.
