### ISSUE TITLE
Use more than one Apds9930

### ISSUE THREAD

**Issue by safeci** [Depau/APDS9930#22]
I need to use 5 apds9930 sensors simultaneously since I am making a line follower robot.
And I can't change the factory I2C address to read the different sensors.
Can you tell me how you can change the factory I2C address of these sensors?

**Comment by depau** [comment]
You can't 🤷‍♂️ if you Google "multiple i2c same address" you can find some devices that can be put between the Arduino and the sensor to change the address.

Or you could use software i2c but i doubt it's gonna work with 5 of them.
