### ISSUE TITLE
APDS9930 apds = APDS9930(); ?

### ISSUE THREAD

**Issue by cheetahkid** [Depau/APDS9930#3]
I see it as correct but I keep getting error :-
On ProximitySensor.ino and
ProximityInterrupt.ino

Using library MDWire at version 1.0 in folder: C:\Users\cheetahkid\Dropbox\Project\libraries\MDWire 
Using library APDS9930-master at version 1.5.1 in folder: C:\Users\cheetahkid\Dropbox\Project\libraries\APDS9930-master 
exit status 1
redefinition of 'APDS9930 apds'

**Comment by depau** [comment]
@cheetahkid Try removing the MDWire directory or moving it somewhere outside of Arduino's sketchbook directory. Let me know if it solves it. I'll check the issue Better in a few days.

**Comment by cheetahkid** [comment]
I tried that too.

Using library Wire at version 1.0 in folder: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.6.13.0_x64__mdqgnx93n4wtt\hardware\arduino\avr\libraries\Wire 
Using library APDS9930-master at version 1.5.1 in folder: C:\Users\cheetahkid\Dropbox\Project\libraries\APDS9930-master 
exit status 1
redefinition of 'APDS9930 apds'

**Comment by depau** [comment]
@cheetahkid I don't know. I'm on vacation at the moment, I don't have the computer with me. I'll check better as soon as I can.
If you don't mind, can you please send me the list of installed libraries, so I can reconstruct your environment and troubleshoot an eventual environment issue?

**Comment by cheetahkid** [comment]
ok

**Comment by cheetahkid** [comment]
I found the problem, it the MassDuino MD328D program, all I did just close it down and restart the arduino IDE. The genuine Arduino seem fine. And the MDWire also cause same problem.
Error compiling for board MassDuino MD-328D.
Sorry about that. I leave that MassDuino out.
http://www.inhaos.com/product_info.php?products_id=156

**Comment by depau** [comment]
@cheetahkid Conflicting libraries are a common issue with Arduino, and sometimes they're hard to troubleshoot. I'm glad you solved it. I'll close the issue when I have my computer, I'm replying with Telegram at the moment.

**Comment by Davideddu** [comment]
@Davideddu Maybe if I say in a message that it closes #3 it actually does that :/
