### ISSUE TITLE
can't understand the output data 

### ISSUE THREAD

**Issue by hznupeter** [Depau/APDS9930#5]
i use ur code on my uno,the  lines connected just likes urs, as fllow:

```
Arduino Pin 	APDS-9930 Board 	Function
3.3V 	VCC 	Power
GND 	GND 	Ground
A4 	SDA 	I²C Data
A5 	SCL 	I²C Clock
2 	INT 	Interrupt
```

The VL is NC.
I upload the code (ProximitySensor.ino) to the uno,and then, i open the  Serial Monitor, the output like this:

```
------------------------
APDS-9930 - ProximityLED
------------------------
APDS-9930 initialization complete
Proximity sensor is now running
0: 0x5
1: 0xFF
2: 0xFF
3: 0xFF
4: 0xFF
5: 0xFF
6: 0x0
7: 0x0
8: 0x0
9: 0x0
A: 0x32
B: 0x0
C: 0x22
D: 0x0
E: 0x8
F: 0x2E
12: 0x39
13: 0x22
14: 0x0
15: 0x0
16: 0x0
17: 0x0
18: 0x4F
19: 0x1
1E: 0x0
Proximity: 298
Proximity: 271
Proximity: 275
Proximity: 284
Proximity: 283
```

----
the output range from 250 to 320,whatever i put hands above it or not. i can't find the rules .

So, i ask for your help.
waiting!
thank u ！

**Comment by depau** [comment]
@hznupeter Hi @hznupeter, I'm sorry but this is not a bug. Proximity sensors like these are anything but precise. That's the reasons why most phones' proximity sensor drivers only expose near/far states (usually near=0cm and far=5cm). Most phones use avago sensors just like the one you're using.
If you want more a more precise sensor you can look for ultrasound sensors, which, however, usually range from 5cm to 5m, and might be bad for some use cases.

I hope you understand :)

(Closes #5)

**Comment by depau** [comment]
@Depaulicious Also, the ambient light lux value may be inaccurate (raw ch0/ch1 values are more precise and make more sense, even though their unit is unspecified)

**Comment by hznupeter** [comment]
@Depaulicious Thank you for responding in time.
I made a mistake like you made years ago ,I confused 9960 and 9930.
I buy it from TAOBAO.COM， and the description is not accurate.
i'll buy a piece of 9960 soon,it's so cheap on TAOBAO,it's only take $3.

----

LAST, Mixly is an wonderful software for students and teachers to coding for arduino . Mixly use blocky, drag and drop，just like Scratch(scratch.mit.edu). I'm also one of the Mixly team.
If you can use our software, it is a great honor for us.
[Mixly](https://github.com/xbed/Mixly_Arduino)

**Comment by depau** [comment]
@hznupeter So did I 😂
