### ISSUE TITLE
Ambient light Lux implementation isn't correct

### ISSUE THREAD

**Issue by debsahu** [Depau/APDS9930#6]
For some reason, the ambient light reading are fine under normal lighting conditions. Ambient light values beyond 4096 are shown as negative numbers, don't know why.

### Owner edit:

SI lux value are not correct because of my inability to understand the formulas in the datasheet properly. The procedure needs to be fixed, if anybody has the knowledge to do it properly, feel free to send a PR so we can close this :)

**Comment by depau** [comment]
@debsahu Please give more information for troubleshooting. What channels are you reading?

**Comment by debsahu** [comment]
Thanks for the quick reply. I am using AmbientLightSensor.ino from your library without modification. It reads ambient_light, ch0 and ch1. Under bright lights, ch0 goes to 1023 first, then ch1, but during this time ambient_light values are shown as negative. Do you want serial log from the sensor?

**Comment by depau** [comment]
The _ambient light lux_ value is wrong. I read the datasheet and I didn't understand the formula to calculate it, I did my best to implement it as well as I could understand it. Use `ch0` and `ch1` values at the moment.

If you're able to understand it and implement it better, I'll sure accept a pull request.

**Comment by ElFishi** [comment]
I spotted two problems with your implementation vs the data sheet: 
1) in line 358 you determine iac as the maximum of iac1 and iac2, while in the data sheet it is the max of iac1, iac2 _and 0_. So you have to make sure iac can't go negative.
2) in line 359 you divide by getAmbientLightGain() which is the value of the AGAIN register (0..3). The data sheet isn't clear here, but division by zero is never a good thing. I presume you need to divide by AGAINx, i.e. 1,8,16, or 120 in this part of the formula.

**Comment by depau** [comment]
Hi @ElFishi, thanks for your help.
Would you mind testing the changes and sending a PR? I don't have time for it at the moment.
Thanks

**Comment by debsahu** [comment]
Firstly thank you both for figuring this out.

@ElFishi Regarding point 2, getAmbientLightGain returns non zero value as it's shifted. I've made changes according to your first point and will test it later tonight. If successful, I'll create a PR.

**Comment by depau** [comment]
@debsahu would you mind testing and reviewing #14 and see if it works? Thank you very much!

**Comment by debsahu** [comment]
Sure thing, maybe by end of tomorrow, I'll report back.
