### ISSUE TITLE
Random proximity values

### ISSUE THREAD

**Issue by hanpal** [Depau/APDS9930#7]
I'm getting valid ch0 and ch1 values but proximity looks like random values between 350 and 450, no connection at all to movements in front of the sensor.

Also, from the quick start:

"Select File -> Examples -> APDS9930 -> GestureTest"

There is no such example, that's for 9960 only?

**Comment by hanpal** [comment]
Tried various PPULSE settings. Same random pattern, just different levels.

**Comment by depau** [comment]
The proximity sensor values are unreliable, which is why mobile phones (which use this sensor or similar ones) often give close/far readings only for proximity.

This sensor model does not provide gesture recognition, the 9960, not supported by this library, does.

**Comment by hanpal** [comment]
1. I couldn't even use it for close/far since values are "random".

2. I suggest that you remove the incorrect information on your main page here regarding ""Select File -> Examples -> APDS9930 -> GestureTest", there is no such example using your library.

**Comment by depau** [comment]
@hanpal I will as soon as I have time

**Comment by drsabe86** [comment]
maybe my awnser comes in abit late but i used the 9930 before, and there i had the same issue that proximity is random.
CHECK YOUR BORD! i got 3 purple CMJCU boards and all had an shematic error, the ir led does not get any current! thats why ambient light works but Proximity not!

**Comment by depau** [comment]
If I remember correctly on some board there's a pin to power the LED, you've just got to power it properly (i.e. make sure you put a resistor if it doesn't have any)

**Comment by mrx23dot** [comment]
Could someone tell me what to fix on the board? Proximity works perfectly on 9960 board, but on 9930s there is no IR output at all. Cheers

**Comment by drsabe86** [comment]
There is a resistor missing on the board
________________________________
Von: Kis Gabor <notifications@github.com>
Gesendet: Dienstag, 22. Jänner 2019 23:23:58
An: Depau/APDS9930
Cc: drsabe86; Comment
Betreff: Re: [Depau/APDS9930] Random proximity values (#7)


Could someone tell me what to fix on the board? Proximity works perfectly on 9960 board, but on 9930s there is no IR output at all. Cheers

**Comment by Necron79** [comment]
Connect the VL pin (far left) to the 3.3v power i.e. same as pin VCC (3rd from left) and sensor works for me. Otherwise I think you can solder across the 2 pads on the back of the board but I've not tried that.

**Comment by TheSnyper** [comment]
Can confirm Necron79's fix works.

**Comment by mrx23dot** [comment]
Worked for me
