### ISSUE TITLE
APDS-9930 Breakout Board link

### ISSUE THREAD

**Issue by gknauf** [Depau/APDS9930#9]
Hi Davide,
I think the link to dx.com is nowadays too expensive;
you can get APDS-9930 breakout boards now for ~1€ - take a look [here](https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313.TR0.TRC0.H0.TRS0&_nkw=APDS-9930&_sacat=0) ...

then, as you already stated, the APDS-9930 and APDS-9960 breakout boards are optically fully identical;
I have both (the red ones) and even the PCB print on the back is with both 'APDS-9960', so it makes probably sense to add a small sample which reads the chip id so one can identify what he really got ...

[apds99xx_read_chipid.zip](https://github.com/Depaulicious/APDS9930/files/1189234/apds99xx_read_chipid.zip)

**Comment by depau** [comment]
Hi @gknauf,
I am aware that you can tell the boards apart by reading the ID. However I don't think making a "universal" library would be a very good thing: the boards still require very different code. It's safer to just include the correct library and write code on top of it.

I don't have time to work on it anyway. I'll close this now as *won't fix*, but feel free to work on it and send me pull requests if you have some time.

Thanks for taking your time to contribute to this project.
